import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/ui/Navbar/Navbar'
import SubNavbar from '@/ui/Navbar/SubNavbar'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark'>
      <body className={`${inter.className}`}>
        <Providers>
          <Navbar />
          <SubNavbar />
          <main className='p-5'>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
