import type { Metadata } from 'next'
import { Mountains_of_Christmas } from 'next/font/google'
import './globals.css'
import Navbar from '@/ui/Navbar/Navbar'
import { Providers } from './providers'

const mountainsOfChristmas = Mountains_of_Christmas({
  weight: ['400', '700'],
  subsets: ['latin']
});


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='light'>
      <body className={`antialiased bg-red-500 text-white ${mountainsOfChristmas.className}`}>
        <Providers>
          <Navbar />
          <main className='p-5 max-w-2xl mx-auto'>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
