import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import LayoutSegments from '@/utils/LayoutSegments'
import Navbar from '@/ui/Navbar/Navbar'
import SubNavbar from '@/ui/Navbar/SubNavbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Navbar />
        <SubNavbar />
        <main className='p-5'>
          {children}
        </main>
      </body>
    </html>
  )
}
